### PR TITLE
fix params read issue

### PR DESCRIPTION
**Pull request by eladg**

### CODE REVIEW

**Comment by yules** [comment]
How about reading field name ('username') from an application parameter? just like the redirect :)

**Comment by eladg** [comment]
By saying application parameter, you mean an HTTP parameter? That's exactly what I'm doing here, but notice that `Content-Type` is JSON which mean that the body of the request is actually a JSON not an HTTP parameter list (the regular `index.html?foo=bar&baz=kar`)

**Comment by yules** [comment]
No, i mean which json field to put the user name attribute in. so if we have param
USERNAME_FIELD = 'user_name'
json should be
{user_name: 'yuval@test.com'}

**Comment by eladg** [comment]
Oh, you mean Environment Variable, great idea! But it has nothing to do with this bugfix / pull request :)

**Comment by yules** [comment]
you're right :+1: anyway, code is good. merge it, we'll test it towards the OMG sale

**Comment by eladg** [comment]
@yules: See #4 :)

**Pull request merged**
